Add/pull request template
Octasol/octasol pull request #16
Opened 2024-10-15 10:38 UTC by LaraKraemer

### Describe your changes
I have added a PR template in a designated .github folder. I also moved the code of conduct file into a .github folder. These two steps follow GitHub open-source best practices. 

### Issue ticket number and link
fixes #14 

### Checklist before requesting a review
* [x] I have performed a self-review of my code
* [x] If it is a core feature, I have added thorough tests.
* [x] I have followed the guidelines in the Contributing document.
* [x] I have added / updated documents (for bug fixes / features).

2024-10-17 06:17 UTC, A91y requested changes

2024-10-17 06:17 UTC, A91y commented on .github/pull_request_template.md
> +* [] I have followed the guidelines in the Contributing document.
Please link the Contributing.md page here for direct reference.

2024-10-17 13:08 UTC, LaraKraemer commented
Added the reference link

2024-10-18 04:33 UTC, A91y approved these changes
lgtm

2024-10-18 04:33 UTC, A91y commented
Thanks @LaraKraemer

2024-10-18 04:33 UTC, merged